name: install crosstool-ng

description: |
  This action installs crosstool-ng on the runner.

inputs:
  version:
    description: 'The version of the toolchain to install.'
    required: true

  target:
    description: 'The toolchain to install.'
    required: true

runs:
  using: composite
  steps:
    - name: clone
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ${{ inputs.version }}
        path: /tmp/crosstool-ng-pre-build

    - name: upload toolchain
      working-directory: /tmp/crosstool-ng-pre-build
      shell: bash
      run: |
        git switch ${{ inputs.version }}
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        rm -rf "./${{ inputs.target }}"
        cp -r "/x-tools/${{ inputs.target }}" "./${{ inputs.target }}"

        git add -A
        git commit -m "Add toolchains for ${{ inputs.target }} ${{ inputs.version }}"
        git push

        rm -rf /tmp/crosstool-ng-pre-build
