name: install cross-compilation toolchain for sparcv9-sun-solaris
author: "oligamiq"

description: |
  This action installs a cross-compilation toolchain on the runner with build.sh script.

runs:
  using: 'composite'
  steps:
    - name: install toolchain
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y software-properties-common libgmp-dev libmpfr-dev libmpc-dev
        sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
        sudo apt-key adv --batch --yes --keyserver keyserver.ubuntu.com --recv-keys 74DA7924C5513486
        sudo add-apt-repository -y 'deb https://apt.dilos.org/dilos dilos2 main'
        mkdir -p ~/build
        cd ~/build
        rm -rf solaris
        rm -rf gcc
        rm -rf /usr/local/sparcv9-sun-solaris2.10
        bash '${{ github.action_path }}/build-solaris-toolchain.sh' sparcv9 sparcv9 solaris-sparc sun
        cd /
        rm -rf ~/build/
        sudo ln -sf /usr/local/bin/sparcv9-sun-solaris2.10-gcc /usr/local/bin/sparcv9-sun-solaris-gcc
        sudo ln -sf /usr/local/bin/sparcv9-sun-solaris2.10-g++ /usr/local/bin/sparcv9-sun-solaris-g++
        sudo ln -sf /usr/local/bin/sparcv9-sun-solaris2.10-ar /usr/local/bin/sparcv9-sun-solaris-ar
