/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RWALL_H_RPCGEN
#define _RWALL_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define WALLPROG 100008
#define WALLVERS 1
#define WALLPROC_WALL 2

__BEGIN_DECLS
void *wallproc_wall_1(char **, CLIENT *);
void *wallproc_wall_1_svc(char **, struct svc_req *);
__END_DECLS

#endif /* !_RWALL_H_RPCGEN */
