/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SM_INTER_H_RPCGEN
#define _SM_INTER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define SM_MAXSTRLEN 1024

struct sm_name {
	char *mon_name;
};
typedef struct sm_name sm_name;

struct my_id {
	char *my_name;
	int my_prog;
	int my_vers;
	int my_proc;
};
typedef struct my_id my_id;

struct mon_id {
	char *mon_name;
	struct my_id my_id;
};
typedef struct mon_id mon_id;

struct mon {
	struct mon_id mon_id;
	char priv[16];
};
typedef struct mon mon;

struct stat_chge {
	char *mon_name;
	int state;
};
typedef struct stat_chge stat_chge;

struct sm_stat {
	int state;
};
typedef struct sm_stat sm_stat;

enum res {
	stat_succ = 0,
	stat_fail = 1
};
typedef enum res res;

struct sm_stat_res {
	res res_stat;
	int state;
};
typedef struct sm_stat_res sm_stat_res;

struct status {
	char *mon_name;
	int state;
	char priv[16];
};
typedef struct status status;

__BEGIN_DECLS
bool_t xdr_sm_name(XDR *, sm_name *);
bool_t xdr_my_id(XDR *, my_id *);
bool_t xdr_mon_id(XDR *, mon_id *);
bool_t xdr_mon(XDR *, mon *);
bool_t xdr_stat_chge(XDR *, stat_chge *);
bool_t xdr_sm_stat(XDR *, sm_stat *);
bool_t xdr_res(XDR *, res *);
bool_t xdr_sm_stat_res(XDR *, sm_stat_res *);
bool_t xdr_status(XDR *, status *);
__END_DECLS

#define SM_PROG 100024
#define SM_VERS 1
#define SM_STAT 1
#define SM_MON 2
#define SM_UNMON 3
#define SM_UNMON_ALL 4
#define SM_SIMU_CRASH 5
#define SM_NOTIFY 6

__BEGIN_DECLS
struct sm_stat_res *sm_stat_1(struct sm_name *, CLIENT *);
struct sm_stat_res *sm_stat_1_svc(struct sm_name *, struct svc_req *);
struct sm_stat_res *sm_mon_1(struct mon *, CLIENT *);
struct sm_stat_res *sm_mon_1_svc(struct mon *, struct svc_req *);
struct sm_stat *sm_unmon_1(struct mon_id *, CLIENT *);
struct sm_stat *sm_unmon_1_svc(struct mon_id *, struct svc_req *);
struct sm_stat *sm_unmon_all_1(struct my_id *, CLIENT *);
struct sm_stat *sm_unmon_all_1_svc(struct my_id *, struct svc_req *);
void *sm_simu_crash_1(void *, CLIENT *);
void *sm_simu_crash_1_svc(void *, struct svc_req *);
void *sm_notify_1(struct stat_chge *, CLIENT *);
void *sm_notify_1_svc(struct stat_chge *, struct svc_req *);
__END_DECLS

#endif /* !_SM_INTER_H_RPCGEN */
