/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _YPPASSWD_H_RPCGEN
#define _YPPASSWD_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct x_passwd {
	char *pw_name;
	char *pw_passwd;
	int pw_uid;
	int pw_gid;
	char *pw_gecos;
	char *pw_dir;
	char *pw_shell;
};
typedef struct x_passwd x_passwd;

struct yppasswd {
	char *oldpass;
	x_passwd newpw;
};
typedef struct yppasswd yppasswd;

__BEGIN_DECLS
bool_t xdr_x_passwd(XDR *, x_passwd *);
bool_t xdr_yppasswd(XDR *, yppasswd *);
__END_DECLS

#define YPPASSWDPROG 100009
#define YPPASSWDVERS 1
#define YPPASSWDPROC_UPDATE 1

__BEGIN_DECLS
int *yppasswdproc_update_1(yppasswd *, CLIENT *);
int *yppasswdproc_update_1_svc(yppasswd *, struct svc_req *);
__END_DECLS

#endif /* !_YPPASSWD_H_RPCGEN */
