[llvm]
targets = "AArch64"
experimental-targets = ""

[target.aarch64-unknown-linux-gnu]
cc = "aarch64-linux-gnu-gcc"
cxx = "aarch64-linux-gnu-g++"
ar = "aarch64-linux-gnu-ar"
ranlib = "aarch64-linux-gnu-ranlib"
linker = "aarch64-linux-gnu-gcc"
