name: install cross-compilation toolchain for powerpc64le-unknown-linux-gnu
author: "oligamiq"

description: |
  This action installs a cross-compilation toolchain on the runner with build.sh script.

runs:
  using: 'composite'
  steps:
    - name: install toolchain
      shell: bash
      run: |
        apt-get update
        apt-get install -y --no-install-recommends automake bison bzip2 ca-certificates cmake curl file flex g++ gawk gdb git gperf help2man libncurses-dev libssl-dev libtool-bin make ninja-build patch pkg-config python3 rsync sudo texinfo unzip wget xz-utils
        sudo apt install -y build-essential
        sudo apt install -y rpm2cpio cpio
        bash '${{ github.action_path }}/build-powerpc64le-toolchain.sh'
