name: test compile

description: |
  Run the compile test for the toolchain.

inputs:
  compiler:
    description: 'The toolchain to test.'
    required: true

  compiler_plus_plus:
    description: 'The toolchain to test.'
    required: true

runs:
  using: composite
  steps:
    - name: create .c file
      shell: bash
      run: |
        # Run hello world program
        cat > hello.c <<EOF
        #include <stdio.h>
        int main() {
          printf("Hello, world!\n");
          return 0;
        }
        EOF

    - name: compile
      shell: bash
      run: |
        # Compile the program
        ${{ inputs.compiler }} hello.c -o hello

    - name: create .cpp file
      shell: bash
      run: |
        # Run hello world program
        cat > hello.cpp <<EOF
        #include <iostream>
        int main() {
          std::cout << "Hello, world!" << std::endl;
          return 0;
        }
        EOF

    - name: compile
      shell: bash
      run: |
        # Compile the program
        ${{ inputs.compiler_plus_plus }} hello.cpp -o hello
