/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/x-tools/sparcv9-sun-solaris2.10/sysroot/usr/include/sys/varargs.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

#ifdef __STDC__
  #include <stdarg.h>
#else
  #include <varargs.h>
#endif
