name: create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the toolchain to build'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: adjust permissions
        uses: ./.github/actions/permission

      - name: switch branch
        run: |
          git pull
          git branch -a
          git switch ${{ github.event.inputs.version }}

      - name: create release
        run: |
          # targets
          TARGETS=(
            "aarch64-unknown-linux-gnu"
            "aarch64-unknown-linux-musl"
            "arm-unknown-linux-gnueabi"
            "arm-unknown-linux-gnueabihf"
            "arm-unknown-linux-musleabi"
            "arm-unknown-linux-musleabihf"
            "armv7-unknown-linux-gnueabihf"
            "i586-unknown-linux-gnu"
            "i686-unknown-linux-gnu"
            "i686-unknown-linux-musl"
            "loongarch64-unknown-linux-gnu"
            "loongarch64-unknown-linux-musl"
            "powerpc-unknown-linux-gnu"
            "powerpc64-unknown-linux-gnu"
            "powerpc64le-unknown-linux-gnu"
            "riscv64-unknown-linux-musl"
            "riscv64gc-unknown-linux-gnu"
            "s390x-unknown-linux-gnu"
            "sparcv9-sun-solaris"
            "x86_64-unknown-freebsd"
            "x86_64-unknown-illumos"
            "x86_64-unknown-linux-musl"
            "x86_64-unknown-netbsd"
            # "xxxxxx-unknown-fuchsia"
          )
          mkdir -p x-tools
          for target in "${TARGETS[@]}"; do
            tar -czf "x-tools/${target}.tar.gz" "${target}"
          done

          echo "x-tools"

          # sysroot
          mkdir -p sysroot
          cd musl-sysroot
          TARGETS=(
            "i586"
            "riscv64gc"
          )
          for target in "${TARGETS[@]}"; do
            mv "${target}" "${target}-unknown-linux-musl"
            tar -czf "../sysroot/${target}-unknown-linux-musl.tar.gz" "${target}-unknown-linux-musl"
          done

          TARGETS=(
            "armv5te"
            "armv7"
          )
          for target in "${TARGETS[@]}"; do
            mv "${target}" "${target}-unknown-linux-musleabi"
            tar -czf "../sysroot/${target}-unknown-linux-musleabi.tar.gz" "${target}-unknown-linux-musleabi"
          done

          TARGETS=(
            "armv7" # armv7hf
          )
          for target in "${TARGETS[@]}"; do
            mv "${target}hf" "${target}-unknown-linux-musleabihf"
            tar -czf "../sysroot/${target}-unknown-linux-musleabihf.tar.gz" "${target}-unknown-linux-musleabihf"
          done

      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            x-tools/*.tar.gz, sysroot/*.tar.gz
          tag: "${{ github.event.inputs.version }}-release"
          allowUpdates: true
          prerelease: true
