name: Build toolchains for musl

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the toolchain to build'
        required: true
        default: 'v0.1.0'

permissions:
  packages: write
  contents: write

jobs:
  cp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: adjust permissions
        uses: ./.github/actions/permission

      - name: build musl sysroot
        run: |
          cd /tmp
          rm -rf build
          mkdir build
          cd build
          bash -x '${{ github.workspace }}/scripts/musl.sh' riscv64gc
          cd /tmp
          rm -rf build

      - name: curl from musl.cc
        run: |
          curl -L https://musl.cc/aarch64-linux-musl-cross.tgz | tar xz
          rm -rf aarch64-unknown-linux-musl
          mv aarch64-linux-musl-cross aarch64-unknown-linux-musl

          curl -L https://musl.cc/riscv64-linux-musl-cross.tgz | tar xz
          rm -rf riscv64-unknown-linux-musl
          mv riscv64-linux-musl-cross riscv64-unknown-linux-musl

          rm -rf riscv64-unknown-linux-musl
          cp -r riscv64-unknown-linux-musl riscv64gc-unknown-linux-musl
          cd riscv64gc-unknown-linux-musl/bin
          sudo apt update
          sudo apt install -y rename
          rename 's/^riscv64-linux-musl/riscv64gc-linux-musl/' riscv64-linux-musl-*
          ln -sf riscv64gc-linux-musl-cc riscv64gc-linux-musl-gcc
          ln -f riscv64gc-linux-musl-g++ riscv64gc-linux-musl-c++
          version=$(ls -l | grep riscv64gc-linux-musl-gcc | sed -e 's/^riscv64gc-linux-musl-gcc-//')
          ln -f riscv64gc-linux-musl-gcc riscv64gc-linux-musl-gcc-$version
          ln -f risv64gc-linux-musl-ld.bfd riscv64gc-linux-musl-ld
          cd ${{ github.workspace }}
          cp -r /musl-riscv64gc ./risv64gc-unknown-linux-musl/test-root

      - name: change branch
        run: |
          git pull
          git branch -a
          git switch ${{ github.event.inputs.version }}

      - name: upload toolchain
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *
          git commit -a -m "Add musl toolchain"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.event.inputs.version }}
