name: Build toolchains for musl

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the toolchain to build'
        required: true
        default: 'v0.1.0'

permissions:
  packages: write
  contents: write

jobs:
  cp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: adjust permissions
        uses: ./.github/actions/permission

      - name: curl from musl.cc
        run: |
          curl -L https://musl.cc/aarch64-linux-musl-cross.tgz | tar xz
          rm -rf aarch64-unknown-linux-musl
          mv aarch64-linux-musl-cross aarch64-unknown-linux-musl

          curl -L https://musl.cc/riscv64-linux-musl-cross.tgz | tar xz
          rm -rf riscv64-unknown-linux-musl
          mv riscv64-linux-musl-cross riscv64-unknown-linux-musl
          echo '${{ github.workspace }}/riscv64-unknown-linux-musl/bin' >> $GITHUB_PATH

          curl -L https://musl.cc/x86_64-linux-musl-cross.tgz | tar xz
          rm -rf x86_64-unknown-linux-musl
          mv x86_64-linux-musl-cross x86_64-unknown-linux-musl

          curl -L https://musl.cc/arm-linux-musleabi-cross.tgz | tar xz
          rm -rf arm-unknown-linux-musleabi
          mv arm-linux-musleabi-cross arm-unknown-linux-musleabi
          echo '${{ github.workspace }}/arm-unknown-linux-musleabi/bin' >> $GITHUB_PATH

          curl -L https://musl.cc/arm-linux-musleabihf-cross.tgz | tar xz
          rm -rf arm-unknown-linux-musleabihf
          mv arm-linux-musleabihf-cross arm-unknown-linux-musleabihf

          curl -L https://musl.cc/i686-linux-musl-cross.tgz | tar xz
          rm -rf i686-unknown-linux-musl
          mv i686-linux-musl-cross i686-unknown-linux-musl
          echo '${{ github.workspace }}/i686-unknown-linux-musl/bin' >> $GITHUB_PATH

      - name: build musl sysroot for riscv64gc
        env:
          CC: riscv64-linux-musl-gcc
          CXX: riscv64-linux-musl-g++
        run: |
          cd /tmp
          rm -rf build
          mkdir build
          cd build
          bash -x '${{ github.workspace }}/scripts/musl.sh' riscv64gc
          cd /tmp
          rm -rf build

      - name: build musl sysroot for armv5te
        env:
          CC: arm-linux-musleabi-gcc
          CXX: arm-linux-musleabi-g++
          AR: arm-linux-musleabi-ar
          RANLIB: arm-linux-musleabi-ranlib
          CFLAGS: "-march=armv5te -marm -mfloat-abi=soft"
          CXXFLAGS: "-march=armv5te -marm -mfloat-abi=soft"
        run: |
          cd /tmp
          rm -rf build
          mkdir build
          cd build
          bash -x '${{ github.workspace }}/scripts/musl.sh' armv5te --target=armv5te
          cd /tmp
          rm -rf build

      - name: build musl sysroot for armv7
        env:
          CC: arm-linux-musleabi-gcc
          CXX: arm-linux-musleabi-g++
          CFLAGS: '-march=armv7-a'
          CXXFLAGS: '-march=armv7-a'
        run: |
          cd /tmp
          rm -rf build
          mkdir build
          cd build
          bash -x '${{ github.workspace }}/scripts/musl.sh' armv7
          cd /tmp
          rm -rf build

      - name: build musl sysroot for i586
        env:
          CC: i686-linux-musl-gcc
          CXX: i686-linux-musl-g++
          CFLAGS: '-m32 -Wa,-mrelax-relocations=no'
          CXXFLAGS: '-m32 -Wa,-mrelax-relocations=no'
        run: |
          cd /tmp
          rm -rf build
          mkdir build
          cd build
          bash -x '${{ github.workspace }}/scripts/musl.sh' i586 --target=i586
          cd /tmp
          rm -rf build

      - name: sysroot
        run: |
          # only sysroot target
          mkdir -p sysroot
          cp -r /musl-riscv64gc sysroot/riscv64gc
          cp -r /musl-armv5te sysroot/armv5te
          cp -r /musl-i586 sysroot/i586


      - name: change branch
        run: |
          git pull
          git branch -a
          git switch ${{ github.event.inputs.version }}

      - name: upload toolchain
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *
          git commit -a -m "Add musl toolchain"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.event.inputs.version }}
